version: '3'
services:
  background_remover:
    build: .
    container_name: background_remover
    volumes:
      - ./input:/data/input
      - ./output:/data/output
    working_dir: /app
    entrypoint: ["bash", "-c"]
    command: ["python process_images.py /data/input/* -o /data/output"]
